# Generated by Django 2.0.5 on 2018-07-17 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0006_auto_20180710_1113'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='company',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
