# Generated by Django 2.0.5 on 2018-07-26 06:26

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(db_index=True, max_length=16)),
                ('company_hash_id', models.CharField(db_index=True, max_length=16)),
                ('name', models.CharField(default='', max_length=255)),
                ('region', models.CharField(blank=True, default='', max_length=100)),
                ('district', models.CharField(blank=True, default='', max_length=100)),
                ('city', models.CharField(blank=True, default='', max_length=50)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('images', models.TextField(blank=True, default='')),
                ('video', models.TextField(blank=True, default='')),
                ('coordinates', models.TextField(blank=True, default='')),
                ('currency', models.CharField(blank=True, default='', max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Company')),
            ],
            options={
                'db_table': 'building',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(max_length=16, null=True)),
                ('house_hash_id', models.CharField(db_index=True, max_length=16)),
                ('flat_schema_hash_id', models.CharField(db_index=True, max_length=16)),
                ('flat_type_hash_id', models.CharField(db_index=True, max_length=16, null=True)),
                ('floor', models.PositiveIntegerField()),
                ('entrance', models.PositiveIntegerField()),
                ('number', models.CharField(blank=True, max_length=255, null=True)),
                ('area', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('windows', models.TextField(blank=True)),
                ('status', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'building_house_flats',
                'ordering': ['id'],
            },
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='FlatSchema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(db_index=True, max_length=16)),
                ('house_hash_id', models.CharField(db_index=True, max_length=16)),
                ('type', models.CharField(max_length=100)),
                ('image', models.CharField(blank=True, default='', max_length=255)),
                ('number_of_balcony', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('number_of_loggia', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'building_house_flats_schemas',
                'ordering': ['id'],
            },
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='FlatType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(db_index=True, max_length=16)),
                ('house_hash_id', models.CharField(db_index=True, max_length=16)),
                ('floor_type_hash_id', models.CharField(db_index=True, max_length=16)),
                ('coordinates', models.TextField()),
            ],
            options={
                'db_table': 'building_house_flats_types',
                'ordering': ['id'],
            },
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(db_index=True, max_length=16)),
                ('house_hash_id', models.CharField(db_index=True, max_length=16)),
                ('floor_type_hash_id', models.CharField(db_index=True, max_length=16, null=True)),
                ('number', models.IntegerField()),
            ],
            options={
                'db_table': 'building_house_floors',
                'ordering': ['id'],
            },
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='FloorType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(db_index=True, max_length=16)),
                ('house_hash_id', models.CharField(db_index=True, max_length=16, null=True)),
                ('image', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'building_house_floors_types',
                'ordering': ['id'],
            },
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='FloorTypeEntrance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(max_length=16)),
                ('floor_type_hash_id', models.CharField(max_length=16)),
                ('number', models.PositiveIntegerField()),
                ('number_of_flats', models.PositiveIntegerField()),
                ('floor_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildings.FloorType')),
            ],
            options={
                'db_table': 'building_house_floor_type_entrances',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(db_index=True, max_length=16)),
                ('building_hash_id', models.CharField(db_index=True, max_length=16)),
                ('number_of_floors', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('living_floors', models.TextField(blank=True, default='')),
                ('number_of_entrance', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('number_of_flat', models.PositiveIntegerField(blank=True, null=True)),
                ('street_name', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=255)),
                ('finishing', models.TextField(blank=True, default='')),
                ('materials', models.TextField(blank=True, default='')),
                ('stage_development', models.CharField(blank=True, default='', max_length=100)),
                ('start_development', models.DateField(blank=True, null=True)),
                ('end_development', models.DateField(blank=True, null=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildings.Building')),
            ],
            options={
                'db_table': 'building_houses',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='floortype',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildings.House'),
        ),
        migrations.AddField(
            model_name='floor',
            name='floor_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='buildings.FloorType'),
        ),
        migrations.AddField(
            model_name='floor',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildings.House'),
        ),
        migrations.AddField(
            model_name='flattype',
            name='floor_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildings.FloorType'),
        ),
        migrations.AddField(
            model_name='flattype',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildings.House'),
        ),
        migrations.AddField(
            model_name='flatschema',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildings.House'),
        ),
        migrations.AddField(
            model_name='flat',
            name='flat_schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildings.FlatSchema'),
        ),
        migrations.AddField(
            model_name='flat',
            name='flat_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='buildings.FlatType'),
        ),
        migrations.AddField(
            model_name='flat',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildings.House'),
        ),
    ]
