# Generated by Django 2.0.5 on 2018-07-17 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='building',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='house',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='house',
            name='end_development',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='start_development',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
