# Generated by Django 2.0.5 on 2018-07-26 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flattype',
            name='number_of_flats',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
