# Generated by Django 2.0.5 on 2018-07-27 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='floortypeentrance',
            name='floor_type',
        ),
        migrations.DeleteModel(
            name='FloorTypeEntrance',
        ),
    ]
