# Generated by Django 2.0.5 on 2018-08-01 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0004_auto_20180730_0955'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='flattype',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='flattype',
            name='number_of_flats',
        ),
    ]
