# Generated by Django 2.0.5 on 2018-09-05 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0005_auto_20180801_1048'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='flat',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='floortype',
            name='clone_floors',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
