# Generated by Django 2.0.5 on 2018-09-17 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0009_flattype_entrance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flattype',
            name='number',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
