# Generated by Django 2.0.5 on 2018-09-19 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0010_auto_20180917_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flattype',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
