# Generated by Django 2.0.5 on 2018-09-25 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0012_flatschema_number_of_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='flattype',
            name='flat_schema',
            field=models.ForeignKey(default=36, on_delete=django.db.models.deletion.CASCADE, to='buildings.FlatSchema'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flattype',
            name='flat_schema_hash_id',
            field=models.CharField(db_index=True, default='9fad2226', max_length=16),
            preserve_default=False,
        ),
    ]
