# Generated by Django 2.0.5 on 2018-09-27 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0013_auto_20180925_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
