# Generated by Django 2.0.5 on 2018-09-28 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0014_flat_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='area',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
