# Generated by Django 2.0.5 on 2018-10-08 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0016_flattype_windows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='living_floors',
            field=models.TextField(default=''),
        ),
    ]
